# Generated by Django 2.1.5 on 2019-01-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_auto_20190105_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegacia',
            name='id_delegacia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
